language: node_js

os:
  - linux

dist: trusty

node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"

before_script:
  - sudo npm link ../ems

env:
  - CXX=g++-4.8

sudo: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
