language: node_js

os:
  - linux
  - osx

dist: trusty

node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"


matrix:
  include:
    - os: linux
      env: CXX=g++-4.8
    - os: osx
      env:

sudo: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

